services:
  - type: web
    name: packnexa-backend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5050
      - key: DATABASE_URL
        fromDatabase:
          name: packnexa-db
          column: connectionString
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: BCRYPT_SALT_ROUND
        value: "10"
      - key: JWT_ACCESS_EXPIRES
        value: "1d"
      - key: JWT_REFRESH_EXPIRES
        value: "7d"

databases:
  - name: packnexa-db
    databaseName: packnexa
    user: packnexa_user
    plan: free # Change to 'standard' for production
